package dev.resolvedor.pos.inventory.management;

import com.unicenta.basic.BasicException;
import com.unicenta.beans.DateUtils;
import com.unicenta.data.gui.ComboBoxValModel;
import com.unicenta.data.loader.LocalRes;
import com.unicenta.data.loader.SentenceList;
import com.unicenta.format.Formats;
import com.unicenta.pos.forms.AppLocal;
import com.unicenta.pos.forms.AppView;
import com.unicenta.pos.forms.BeanFactoryApp;
import com.unicenta.pos.forms.BeanFactoryException;
import com.unicenta.pos.forms.DataLogicSales;
import com.unicenta.pos.forms.JPanelView;
import com.unicenta.pos.inventory.InventoryLine;
import com.unicenta.pos.inventory.InventoryRecord;
import com.unicenta.pos.inventory.LocationInfo;
import com.unicenta.pos.inventory.MovementReason;
import com.unicenta.pos.suppliers.DataLogicSuppliers;
import com.unicenta.pos.suppliers.SupplierInfo;
import com.unicenta.pos.ticket.ProductInfoExt;
import com.unicenta.pos.ticket.TaxInfo;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lombok.extern.slf4j.Slf4j;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Jorge Luis
 * @web https://resolvedor.dev
 * @mail jorgeluis@resolvedor.dev
 */
@Slf4j
public class PurchaseEditor extends JPanel implements JPanelView, BeanFactoryApp {

    private AppView app;

    private DataLogicPurchase dlPurchase;
    private DataLogicSuppliers dlSupplier;
    private DataLogicSales dlSales;

    private ComboBoxValModel modelReason;
    private ComboBoxValModel modelSupplier;
    private ComboBoxValModel modelTaxSupport;
    private ComboBoxValModel modelDocumentType;
    private ComboBoxValModel modelLocation;

    private SentenceList sentSupplier;
    private SentenceList sentTaxSupport;

    private PurchaseInfo purchase;
    private final JPurchaseLines purchaseLines;

    public PurchaseEditor() {
        initComponents();

        purchase = new PurchaseInfo();
        purchaseLines = new JPurchaseLines();
        panelLines.add(purchaseLines, BorderLayout.CENTER);

        AutoCompleteDecorator.decorate(cboSupplier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdSave = new javax.swing.JButton();
        cmdInsert = new javax.swing.JButton();
        panelHead = new javax.swing.JPanel();
        lblNumber = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        lblReason = new javax.swing.JLabel();
        cboReason = new javax.swing.JComboBox<>();
        lblCreatedAt = new javax.swing.JLabel();
        txtCreatedAt = new javax.swing.JTextField();
        lblSupplier = new javax.swing.JLabel();
        cboSupplier = new javax.swing.JComboBox<>();
        lblDescription = new javax.swing.JLabel();
        txtObservation = new javax.swing.JTextField();
        panelTax = new javax.swing.JPanel();
        lblTaxSupport = new javax.swing.JLabel();
        cboTaxSupport = new javax.swing.JComboBox<>();
        lblDocument = new javax.swing.JLabel();
        cboDocumentType = new javax.swing.JComboBox<>();
        lblSerie = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        lblDatePurchase = new javax.swing.JLabel();
        txtDatePurchase = new javax.swing.JTextField();
        lblAuthorization = new javax.swing.JLabel();
        txtAuthorization = new javax.swing.JTextField();
        panelProduct = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboLocation = new javax.swing.JComboBox<>();
        panelLines = new javax.swing.JPanel();
        panelAction = new javax.swing.JPanel();
        cmdDeleteProduct = new javax.swing.JButton();
        cmdFindProduct = new javax.swing.JButton();
        cmdDeleteAll = new javax.swing.JButton();
        panelTotal = new javax.swing.JPanel();
        lblSubtotalTitle = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblTaxTitle = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblTotalTitle = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        cmdSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unicenta/images/ok.png"))); // NOI18N
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });

        cmdInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unicenta/images/editnew.png"))); // NOI18N
        cmdInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdInsertActionPerformed(evt);
            }
        });

        panelHead.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        lblNumber.setText(bundle.getString("label.Number")); // NOI18N
        lblNumber.setMaximumSize(new java.awt.Dimension(120, 26));
        lblNumber.setMinimumSize(new java.awt.Dimension(120, 26));
        lblNumber.setPreferredSize(new java.awt.Dimension(99, 26));

        txtNumber.setMaximumSize(new java.awt.Dimension(240, 36));
        txtNumber.setPreferredSize(new java.awt.Dimension(240, 36));

        lblReason.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReason.setText(bundle.getString("label.stockreason")); // NOI18N
        lblReason.setMaximumSize(new java.awt.Dimension(120, 26));
        lblReason.setMinimumSize(new java.awt.Dimension(120, 26));
        lblReason.setPreferredSize(new java.awt.Dimension(99, 26));

        lblCreatedAt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCreatedAt.setLabelFor(txtCreatedAt);
        lblCreatedAt.setText(bundle.getString("label.date")); // NOI18N
        lblCreatedAt.setMaximumSize(new java.awt.Dimension(120, 26));
        lblCreatedAt.setMinimumSize(new java.awt.Dimension(120, 26));
        lblCreatedAt.setPreferredSize(new java.awt.Dimension(99, 26));

        txtCreatedAt.setPreferredSize(new java.awt.Dimension(240, 36));

        lblSupplier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSupplier.setText(bundle.getString("label.supplier")); // NOI18N
        lblSupplier.setMaximumSize(new java.awt.Dimension(120, 26));
        lblSupplier.setMinimumSize(new java.awt.Dimension(120, 26));
        lblSupplier.setPreferredSize(new java.awt.Dimension(99, 26));

        lblDescription.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDescription.setText(bundle.getString("label.item2")); // NOI18N
        lblDescription.setMaximumSize(new java.awt.Dimension(120, 26));
        lblDescription.setMinimumSize(new java.awt.Dimension(120, 26));
        lblDescription.setPreferredSize(new java.awt.Dimension(99, 26));

        txtObservation.setPreferredSize(new java.awt.Dimension(600, 36));

        javax.swing.GroupLayout panelHeadLayout = new javax.swing.GroupLayout(panelHead);
        panelHead.setLayout(panelHeadLayout);
        panelHeadLayout.setHorizontalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeadLayout.createSequentialGroup()
                        .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtObservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelHeadLayout.createSequentialGroup()
                        .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboReason, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeadLayout.createSequentialGroup()
                                .addComponent(lblCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeadLayout.createSequentialGroup()
                                .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelHeadLayout.setVerticalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboReason, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtObservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTax.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("label.purchase"))); // NOI18N

        lblTaxSupport.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaxSupport.setText(bundle.getString("label.taxSupport")); // NOI18N
        lblTaxSupport.setPreferredSize(new java.awt.Dimension(99, 26));

        cboTaxSupport.setPreferredSize(new java.awt.Dimension(180, 36));

        lblDocument.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDocument.setText(bundle.getString("label.supplierdocment")); // NOI18N
        lblDocument.setPreferredSize(new java.awt.Dimension(99, 26));

        cboDocumentType.setPreferredSize(new java.awt.Dimension(180, 36));

        lblSerie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerie.setText(bundle.getString("label.Number")); // NOI18N
        lblSerie.setPreferredSize(new java.awt.Dimension(99, 26));

        txtSerie.setPreferredSize(new java.awt.Dimension(240, 36));

        lblDatePurchase.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDatePurchase.setText(bundle.getString("label.date")); // NOI18N
        lblDatePurchase.setPreferredSize(new java.awt.Dimension(99, 26));

        txtDatePurchase.setPreferredSize(new java.awt.Dimension(180, 36));
        txtDatePurchase.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDatePurchaseFocusGained(evt);
            }
        });

        lblAuthorization.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAuthorization.setText(bundle.getString("label.authorization")); // NOI18N
        lblAuthorization.setPreferredSize(new java.awt.Dimension(99, 26));

        txtAuthorization.setPreferredSize(new java.awt.Dimension(530, 36));

        javax.swing.GroupLayout panelTaxLayout = new javax.swing.GroupLayout(panelTax);
        panelTax.setLayout(panelTaxLayout);
        panelTaxLayout.setHorizontalGroup(
            panelTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTaxLayout.createSequentialGroup()
                        .addComponent(lblTaxSupport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboTaxSupport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboDocumentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTaxLayout.createSequentialGroup()
                        .addComponent(lblDatePurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDatePurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAuthorization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAuthorization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTaxLayout.setVerticalGroup(
            panelTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxSupport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTaxSupport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDocumentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatePurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatePurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAuthorization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAuthorization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProduct.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(bundle.getString("label.location")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(99, 26));

        javax.swing.GroupLayout panelProductLayout = new javax.swing.GroupLayout(panelProduct);
        panelProduct.setLayout(panelProductLayout);
        panelProductLayout.setHorizontalGroup(
            panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProductLayout.setVerticalGroup(
            panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLines.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelLines.setLayout(new java.awt.BorderLayout());

        panelAction.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmdDeleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unicenta/images/editdelete.png"))); // NOI18N
        cmdDeleteProduct.setPreferredSize(new java.awt.Dimension(45, 45));
        cmdDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteProductActionPerformed(evt);
            }
        });

        cmdFindProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unicenta/images/search32.png"))); // NOI18N
        cmdFindProduct.setPreferredSize(new java.awt.Dimension(45, 45));
        cmdFindProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFindProductActionPerformed(evt);
            }
        });

        cmdDeleteAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unicenta/images/sale_delete.png"))); // NOI18N
        cmdDeleteAll.setPreferredSize(new java.awt.Dimension(45, 45));
        cmdDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActionLayout = new javax.swing.GroupLayout(panelAction);
        panelAction.setLayout(panelActionLayout);
        panelActionLayout.setHorizontalGroup(
            panelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdFindProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelActionLayout.setVerticalGroup(
            panelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdFindProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSubtotalTitle.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblSubtotalTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotalTitle.setText(bundle.getString("label.subtotalcash")); // NOI18N

        lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotal.setLabelFor(lblSubtotal);
        lblSubtotal.setText("0.0");

        lblTaxTitle.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblTaxTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaxTitle.setText(bundle.getString("label.taxcash")); // NOI18N

        lblTax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTax.setLabelFor(lblSubtotal);
        lblTax.setText("0.0");

        lblTotalTitle.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblTotalTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalTitle.setText(bundle.getString("label.totalcash")); // NOI18N

        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setLabelFor(lblSubtotal);
        lblTotal.setText("0.0");

        javax.swing.GroupLayout panelTotalLayout = new javax.swing.GroupLayout(panelTotal);
        panelTotal.setLayout(panelTotalLayout);
        panelTotalLayout.setHorizontalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotalTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(lblSubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(lblTaxTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(lblTax, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(lblTotalTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTotalLayout.setVerticalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubtotalTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTaxTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelHead, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cmdSave, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelLines, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdSave)
                    .addComponent(cmdInsert))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
        save();
    }//GEN-LAST:event_cmdSaveActionPerformed

    private void save() {
        if (!validateData()) {
            return;
        }

        MovementReason reason = (MovementReason) modelReason.getSelectedItem();

        try {
            Date d = (Date) Formats.TIMESTAMP.parseValue(txtCreatedAt.getText());
            purchase.setNumber((Integer) dlPurchase.getPurchaseSequence().find());
            purchase.setMoney(app.getActiveCashIndex());
            purchase.setCreatedAt(new Date());
            purchase.setReason((Integer) modelReason.getSelectedKey());
            purchase.setSupplier(modelSupplier.getSelectedKey().toString());

            // Purchase tax support
            purchase.setPurchaseTaxSupport(modelTaxSupport.getSelectedKey().toString());
            purchase.setPurchaseDocument(modelDocumentType.getSelectedKey().toString());
            purchase.setPurchaseReference(txtSerie.getText());
            purchase.setPurchaseDate((Date) Formats.DATE.parseValue(txtDatePurchase.getText()));
            purchase.setPurchaseAuthorization(txtAuthorization.getText());

            purchase.setObservation(txtObservation.getText());

            var result = dlPurchase.savePurchase(purchase, new InventoryRecord(
                    new Date(),
                    reason,
                    (LocationInfo) modelLocation.getSelectedItem(),
                    app.getAppUserView().getUser().getName(),
                    (SupplierInfo) modelSupplier.getSelectedItem(),
                    purchaseLines.getLines(),
                    txtSerie.getText())
            );

            JOptionPane.showMessageDialog(
                    this,
                    AppLocal.getIntString("label.purchase") + " = " + result,
                    LocalRes.getIntString("sgn.success"),
                    JOptionPane.INFORMATION_MESSAGE
            );
        } catch (BasicException ex) {
            log.error(PurchaseEditor.class.getName() + " " + ex.getMessage());
        }

        stateToInsert();
    }

    private boolean validateData() {

        if (modelSupplier.getSelectedKey() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    LocalRes.getIntString("exception.noSupplier"),
                    AppLocal.getIntString("label.supplier"),
                    JOptionPane.OK_OPTION
            );
            cboSupplier.requestFocus();
            return false;
        }

        if (modelTaxSupport.getSelectedKey() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    LocalRes.getIntString("exception.noTaxSupport"),
                    AppLocal.getIntString("label.taxSupport"),
                    JOptionPane.OK_OPTION
            );
            cboTaxSupport.requestFocus();
            return false;
        }

        if (modelDocumentType.getSelectedKey() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    LocalRes.getIntString("exception.noDocumentType"),
                    AppLocal.getIntString("label.supplierdocment"),
                    JOptionPane.OK_OPTION
            );
            cboDocumentType.requestFocus();
            return false;
        }

        if (txtDatePurchase.getText() == null || txtDatePurchase.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    LocalRes.getIntString("exception.noPurchaseDate"),
                    AppLocal.getIntString("label.date"),
                    JOptionPane.OK_OPTION
            );
            txtDatePurchase.requestFocus();
            return false;
        } else {
            try {
                Date d = (Date) Formats.DATE.parseValue(txtDatePurchase.getText());
            } catch (BasicException ex) {
                JOptionPane.showMessageDialog(
                        this,
                        LocalRes.getIntString("exception.noPurchaseDate"),
                        AppLocal.getIntString("label.date"),
                        JOptionPane.OK_OPTION
                );
                txtDatePurchase.requestFocus();
                return false;
            }
        }

        if (txtSerie.getText() == null || txtSerie.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    LocalRes.getIntString("exception.noDocumentNumber"),
                    AppLocal.getIntString("label.Number"),
                    JOptionPane.OK_OPTION
            );
            txtSerie.requestFocus();
            return false;
        }

        if (txtAuthorization.getText() == null || txtAuthorization.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    LocalRes.getIntString("exception.noAuthorization"),
                    AppLocal.getIntString("label.authorization"),
                    JOptionPane.OK_OPTION
            );
            txtAuthorization.requestFocus();
            return false;
        }

        if (purchaseLines.getCount() == 0) {
            JOptionPane.showMessageDialog(
                    this,
                    AppLocal.getIntString("message.productnotselected"),
                    AppLocal.getIntString("Menu.Products"),
                    JOptionPane.OK_OPTION
            );
            return false;
        }

        return true;
    }

    private void cmdInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdInsertActionPerformed
        stateToInsert();
        cboReason.requestFocus();
    }//GEN-LAST:event_cmdInsertActionPerformed

    private void cmdFindProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFindProductActionPerformed
        productFinder();
    }//GEN-LAST:event_cmdFindProductActionPerformed

    private void productFinder() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PurchaseProductDialog dialog = new PurchaseProductDialog(app, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.setVisible(false);
                    }
                });
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
                if (dialog.getReturnStatus() == PurchaseProductDialog.RET_OK) {
                    ProductInfoExt product = dialog.getProduct();
                    incProduct(product, dialog.getTax());
                }
            }
        });
    }

    private void cmdDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteAllActionPerformed
        int res = JOptionPane.showConfirmDialog(this,
                AppLocal.getIntString("message.wannadelete"),
                AppLocal.getIntString("title.editor"),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (res == JOptionPane.YES_OPTION) {

            int i = 0;
            while (i < purchaseLines.getCount()) {
                purchaseLines.deleteLine(i);
                this.purchase.getInvLines().remove(i);
            }
        }
        printInvLines();
    }//GEN-LAST:event_cmdDeleteAllActionPerformed

    private void cmdDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteProductActionPerformed
        int i = purchaseLines.getSelectedRow();

        if (i < 0) {
            Toolkit.getDefaultToolkit().beep();
        } else {
            removeInvLine(i);

        }
        printInvLines();
    }//GEN-LAST:event_cmdDeleteProductActionPerformed

    private void txtDatePurchaseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDatePurchaseFocusGained
        if (txtDatePurchase.getText() == null || txtDatePurchase.getText().isEmpty()) {
            txtDatePurchase.setText(Formats.DATE.formatValue(DateUtils.getToday()));
        }
    }//GEN-LAST:event_txtDatePurchaseFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboDocumentType;
    private javax.swing.JComboBox<String> cboLocation;
    private javax.swing.JComboBox<String> cboReason;
    private javax.swing.JComboBox<String> cboSupplier;
    private javax.swing.JComboBox<String> cboTaxSupport;
    private javax.swing.JButton cmdDeleteAll;
    private javax.swing.JButton cmdDeleteProduct;
    private javax.swing.JButton cmdFindProduct;
    private javax.swing.JButton cmdInsert;
    private javax.swing.JButton cmdSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAuthorization;
    private javax.swing.JLabel lblCreatedAt;
    private javax.swing.JLabel lblDatePurchase;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDocument;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblReason;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalTitle;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTaxSupport;
    private javax.swing.JLabel lblTaxTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalTitle;
    private javax.swing.JPanel panelAction;
    private javax.swing.JPanel panelHead;
    private javax.swing.JPanel panelLines;
    private javax.swing.JPanel panelProduct;
    private javax.swing.JPanel panelTax;
    private javax.swing.JPanel panelTotal;
    private javax.swing.JTextField txtAuthorization;
    private javax.swing.JTextField txtCreatedAt;
    private javax.swing.JTextField txtDatePurchase;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtObservation;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return AppLocal.getIntString("label.purchase");
    }

    @Override
    public void activate() throws BasicException {
        try {
            modelReason = new ComboBoxValModel();
            modelReason.add(MovementReason.IN_PURCHASE);    //Supplier Purchase
            //modelReason.add(MovementReason.OUT_REFUND);   //Supplier Return
            cboReason.setModel(modelReason);

            sentSupplier = dlSupplier.getSupplierList();
            modelSupplier = new ComboBoxValModel(sentSupplier.list());
            cboSupplier.setModel(modelSupplier);

            sentTaxSupport = dlPurchase.getTaxSupportList();
            modelTaxSupport = new ComboBoxValModel(sentTaxSupport.list());
            cboTaxSupport.setModel(modelTaxSupport);

            modelDocumentType = new ComboBoxValModel(
                    dlPurchase.getDocumentTypeList().list()
            );
            cboDocumentType.setModel(modelDocumentType);

            // Load locations
            modelLocation = new ComboBoxValModel(dlSales.getLocationsList().list());
            cboLocation.setModel(modelLocation);

            stateToInsert();
        } catch (BasicException ex) {
            log.error(PurchaseEditor.class.getName() + " " + ex.getMessage());
        }
    }

    @Override
    public boolean deactivate() {
        return true;
    }

    @Override
    public JComponent getComponent() {
        return this;
    }

    @Override
    public void init(AppView app) throws BeanFactoryException {
        this.app = app;

        dlPurchase = (DataLogicPurchase) app.getBean("dev.resolvedor.pos.inventory.management.DataLogicPurchase");
        dlSupplier = (DataLogicSuppliers) app.getBean("com.unicenta.pos.suppliers.DataLogicSuppliers");
        dlSales = (DataLogicSales) app.getBean("com.unicenta.pos.forms.DataLogicSales");
    }

    @Override
    public Object getBean() {
        return this;
    }

    public void stateToInsert() {

        txtNumber.setText(null);
        txtCreatedAt.setText(null);
        txtObservation.setText(null);
        txtSerie.setText(null);
        txtDatePurchase.setText(null);
        txtAuthorization.setText(null);

        modelLocation.setSelectedKey(app.getInventoryLocation());
        modelReason.setSelectedItem(MovementReason.IN_PURCHASE);
        modelSupplier.setSelectedKey(null);
        modelDocumentType.setSelectedKey(null);
        modelTaxSupport.setSelectedKey(null);

        txtNumber.setEnabled(true);
        txtCreatedAt.setEnabled(true);
        txtObservation.setEnabled(true);
        txtSerie.setEnabled(true);
        txtDatePurchase.setEnabled(true);
        txtAuthorization.setEnabled(true);
        cboReason.setEnabled(true);
        cboSupplier.setEnabled(true);

        purchase = new PurchaseInfo();
        purchase.setUser(app.getAppUserView().getUser().getUserInfo());
        purchaseLines.clear();

        cboReason.requestFocus();
    }

    private void incProduct(ProductInfoExt product, TaxInfo tax) {
        addLine(product, product.getQuantity(), product.getTotalCost(), product.getLot(), tax);
        printInvLines();
    }

    private void addLine(ProductInfoExt oProduct, double dpor, double totalCost, String lot, TaxInfo tax) {

        purchaseLines.addLine(new InventoryLine(oProduct, dpor, totalCost, lot, tax));

        this.purchase.getInvLines().add(
                new InventoryLine(oProduct, dpor, totalCost, lot, tax)
        );
    }

    private void removeInvLine(int index) {

        if (index < 0) {
            Toolkit.getDefaultToolkit().beep();
        } else {
            purchaseLines.deleteLine(index);
            this.purchase.getInvLines().remove(index);
        }
    }

    private void printInvLines() {
        for (int i = 0; i < this.purchase.getInvLines().size(); i++) {
            InventoryLine inv = this.purchase.getInvLines().get(i);
//            System.out.println(i + " Product: " + inv.getProductName() + " #: " + inv.getMultiply() + " Total: " + inv.getPrice() * inv.getMultiply());
        }

        lblSubtotal.setText(purchase.printSubTotal());
        lblTax.setText(purchase.printTax());
        lblTotal.setText(purchase.printTotal());
    }
}
