package dev.resolver.pos.dispatcher;

import com.unicenta.basic.BasicException;
import com.unicenta.data.gui.ComboBoxValModel;
import com.unicenta.data.loader.SentenceList;
import com.unicenta.data.user.DirtyManager;
import com.unicenta.data.user.EditorRecord;
import com.unicenta.pos.forms.AppView;
import com.unicenta.pos.suppliers.DataLogicSuppliers;
import java.awt.Component;
import javax.swing.JPanel;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author Jorge Luis
 * @web https://resolvers.dev
 * @mail jorgeluis@resolvers.dev
 */
@Slf4j
public class DispatcherEditor extends JPanel implements EditorRecord {

    private AppView app;
    private Object id;

    private DataLogicSuppliers dlSuppliers;

    private SentenceList sentenceIdentificationType;
    private ComboBoxValModel modelIdentificationType;

    public DispatcherEditor(AppView app, DirtyManager dirty) {
        initComponents();

        this.app = app;
        try {
            dlSuppliers = (DataLogicSuppliers) app.getBean("com.unicenta.pos.suppliers.DataLogicSuppliers");

            sentenceIdentificationType = dlSuppliers.getIdentificationTypeList();
            modelIdentificationType = new ComboBoxValModel(
                    sentenceIdentificationType.list());

            cbxIdentificationType.addActionListener(dirty);
            txtIdentification.getDocument().addDocumentListener(dirty);
            
            cbxIdentificationType.setModel(modelIdentificationType);
        } catch (BasicException ex) {
            log.error(DispatcherEditor.class.getName() + " " + ex.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdentificationType = new javax.swing.JLabel();
        cbxIdentificationType = new javax.swing.JComboBox<>();
        lblIdentification = new javax.swing.JLabel();
        txtIdentification = new javax.swing.JTextField();

        lblIdentificationType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        lblIdentificationType.setText(bundle.getString("label.identificationType")); // NOI18N
        lblIdentificationType.setPreferredSize(new java.awt.Dimension(180, 30));

        cbxIdentificationType.setPreferredSize(new java.awt.Dimension(210, 40));

        lblIdentification.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdentification.setText(bundle.getString("label.suppliertaxid")); // NOI18N
        lblIdentification.setPreferredSize(new java.awt.Dimension(180, 30));

        txtIdentification.setPreferredSize(new java.awt.Dimension(210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdentificationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxIdentificationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxIdentificationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(448, Short.MAX_VALUE))
        );

        cbxIdentificationType.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void writeValueEOF() {

    }

    @Override
    public void writeValueInsert() {

    }

    @Override
    public void writeValueEdit(Object value) {

    }

    @Override
    public void writeValueDelete(Object value) {

    }

    @Override
    public void refresh() {

    }

    @Override
    public Component getComponent() {
        return this;
    }

    @Override
    public Object createValue() throws BasicException {
        return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxIdentificationType;
    private javax.swing.JLabel lblIdentification;
    private javax.swing.JLabel lblIdentificationType;
    private javax.swing.JTextField txtIdentification;
    // End of variables declaration//GEN-END:variables
}
