package dev.joguenco.pos.dispatcher;

import com.unicenta.basic.BasicException;
import com.unicenta.data.gui.ComboBoxValModel;
import com.unicenta.data.loader.SentenceList;
import com.unicenta.data.user.DirtyManager;
import com.unicenta.data.user.EditorRecord;
import com.unicenta.format.Formats;
import com.unicenta.pos.forms.AppLocal;
import com.unicenta.pos.forms.AppView;
import com.unicenta.pos.suppliers.DataLogicSuppliers;

import dev.joguenco.error.ErrorMessage;

import java.awt.Component;
import java.util.UUID;

import javax.swing.JPanel;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author Jorge Luis
 * @web https://resolvers.dev
 * @mail jorgeluis@resolvers.dev
 */
@Slf4j
public class DispatcherEditor extends JPanel implements EditorRecord {

    private AppView app;
    private Object id;

    private DataLogicSuppliers dlSuppliers;

    private SentenceList sentenceIdentificationType;
    private ComboBoxValModel modelIdentificationType;

    public DispatcherEditor(AppView app, DirtyManager dirty) {
        initComponents();

        this.app = app;
        try {
            dlSuppliers = (DataLogicSuppliers) app.getBean("com.unicenta.pos.suppliers.DataLogicSuppliers");

            sentenceIdentificationType = dlSuppliers.getIdentificationTypeList();
            modelIdentificationType = new ComboBoxValModel(
                    sentenceIdentificationType.list());

            cbxIdentificationType.addActionListener(dirty);
            txtIdentification.getDocument().addDocumentListener(dirty);
            txtName.getDocument().addDocumentListener(dirty);
            txtPlate.getDocument().addDocumentListener(dirty);
            txtPhone.getDocument().addDocumentListener(dirty);
            txtDescription.getDocument().addDocumentListener(dirty);
            chkStatus.addActionListener(dirty);

            cbxIdentificationType.setModel(modelIdentificationType);
        } catch (BasicException ex) {
            log.error(DispatcherEditor.class.getName() + " " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdentificationType = new javax.swing.JLabel();
        cbxIdentificationType = new javax.swing.JComboBox<>();
        lblIdentification = new javax.swing.JLabel();
        txtIdentification = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPlate = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        chkStatus = new javax.swing.JCheckBox();
        lblPlate = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        lblIdentificationType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        lblIdentificationType.setText(bundle.getString("label.identificationType")); // NOI18N
        lblIdentificationType.setPreferredSize(new java.awt.Dimension(180, 30));

        cbxIdentificationType.setPreferredSize(new java.awt.Dimension(210, 40));

        lblIdentification.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdentification.setText(bundle.getString("label.suppliertaxid")); // NOI18N
        lblIdentification.setPreferredSize(new java.awt.Dimension(180, 30));

        txtIdentification.setPreferredSize(new java.awt.Dimension(210, 40));

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText(bundle.getString("label.namem")); // NOI18N
        lblName.setPreferredSize(new java.awt.Dimension(180, 30));

        txtName.setPreferredSize(new java.awt.Dimension(360, 40));

        txtPlate.setPreferredSize(new java.awt.Dimension(210, 40));

        txtPhone.setPreferredSize(new java.awt.Dimension(210, 40));

        txtDescription.setPreferredSize(new java.awt.Dimension(360, 40));

        lblPlate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPlate.setText(bundle.getString("label.plate")); // NOI18N
        lblPlate.setPreferredSize(new java.awt.Dimension(180, 30));

        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhone.setText(bundle.getString("label.phone")); // NOI18N
        lblPhone.setPreferredSize(new java.awt.Dimension(180, 30));

        lblDescription.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDescription.setText(bundle.getString("label.item2")); // NOI18N
        lblDescription.setPreferredSize(new java.awt.Dimension(180, 30));

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatus.setText(bundle.getString("label.Status")); // NOI18N
        lblStatus.setPreferredSize(new java.awt.Dimension(180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdentificationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxIdentificationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkStatus))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxIdentificationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkStatus)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        cbxIdentificationType.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void writeValueEOF() {
        id = null;
        modelIdentificationType.setSelectedFirst();
        txtIdentification.setText(null);
        txtName.setText(null);
        txtPlate.setText(null);
        txtPhone.setText(null);
        txtDescription.setText(null);
        chkStatus.setSelected(false);

        cbxIdentificationType.setEnabled(false);
        txtIdentification.setEnabled(false);
        txtName.setEnabled(false);
        txtPlate.setEnabled(false);
        txtPhone.setEnabled(false);
        txtDescription.setEnabled(false);
        chkStatus.setEnabled(false);
    }

    @Override
    public void writeValueInsert() {
        id = null;
        modelIdentificationType.setSelectedFirst();
        txtIdentification.setText(null);
        txtName.setText(null);
        txtPlate.setText(null);
        txtPhone.setText(null);
        txtDescription.setText(null);
        chkStatus.setSelected(true);

        cbxIdentificationType.setEnabled(true);
        txtIdentification.setEnabled(true);
        txtName.setEnabled(true);
        txtPlate.setEnabled(true);
        txtPhone.setEnabled(true);
        txtDescription.setEnabled(true);
        chkStatus.setEnabled(true);

        cbxIdentificationType.requestFocus();
    }

    @Override
    public void writeValueEdit(Object value) {
        Object[] dispatcher = (Object[]) value;
        id = dispatcher[0];
        modelIdentificationType.setSelectedKey(dispatcher[1]);
        txtIdentification.setText((String) dispatcher[2]);
        txtName.setText((String) dispatcher[3]);
        txtPlate.setText((String) dispatcher[4]);
        txtPhone.setText((String) dispatcher[5]);
        txtDescription.setText((String) dispatcher[6]);

        if (Boolean.valueOf(Formats.BOOLEAN.formatValue(dispatcher[7]))) {
            chkStatus.setSelected(true);
        } else {
            chkStatus.setSelected(false);
        }

        cbxIdentificationType.setEnabled(true);
        txtIdentification.setEnabled(true);
        txtName.setEnabled(true);
        txtPlate.setEnabled(true);
        txtPhone.setEnabled(true);
        txtDescription.setEnabled(true);
        chkStatus.setEnabled(true);
    }

    @Override
    public void writeValueDelete(Object value) {
        Object[] dispatcher = (Object[]) value;
        id = dispatcher[0];
        modelIdentificationType.setSelectedKey(dispatcher[1]);
        txtIdentification.setText((String) dispatcher[2]);
        txtName.setText((String) dispatcher[3]);
        txtPlate.setText((String) dispatcher[4]);
        txtPhone.setText((String) dispatcher[5]);
        txtDescription.setText((String) dispatcher[6]);

        if (Boolean.valueOf(Formats.BOOLEAN.formatValue(dispatcher[7]))) {
            chkStatus.setSelected(true);
        } else {
            chkStatus.setSelected(false);
        }

        cbxIdentificationType.setEnabled(false);
        txtIdentification.setEnabled(false);
        txtName.setEnabled(false);
        txtPlate.setEnabled(false);
        txtPhone.setEnabled(false);
        txtDescription.setEnabled(false);
        chkStatus.setEnabled(false);
    }

    @Override
    public void refresh() {
    }

    @Override
    public Component getComponent() {
        return this;
    }

    @Override
    public Object createValue() throws BasicException {
        ErrorMessage validate = validateData();

        if (validate.getIsError()) {
            throw new BasicException(validate.getMessage());
        }

        Object[] dispatcher = new Object[8];
        dispatcher[0] = id == null ? UUID.randomUUID().toString() : id;
        dispatcher[1] = modelIdentificationType.getSelectedKey();
        dispatcher[2] = txtIdentification.getText();
        dispatcher[3] = txtName.getText();
        dispatcher[4] = txtPlate.getText();
        dispatcher[5] = txtPhone.getText();
        dispatcher[6] = txtDescription.getText();
        if (chkStatus.isSelected()) {
            dispatcher[7] = true;
        } else {
            dispatcher[7] = false;
        }

        return dispatcher;
    }

    private ErrorMessage validateData() {
        if (txtName.getText().trim().isEmpty()) {
            return new ErrorMessage(AppLocal.getIntString("message.lot.empty"));
        }
        return new ErrorMessage();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxIdentificationType;
    private javax.swing.JCheckBox chkStatus;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblIdentification;
    private javax.swing.JLabel lblIdentificationType;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPlate;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtIdentification;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPlate;
    // End of variables declaration//GEN-END:variables
}
